export const cardArray = [
  {
    hotelName: "Grand Plaza Hotel",
    location: "Downtown",
    checkInDate: "2023-11-15",
    checkOutDate: "2023-11-20",
    numberOfGuests: 2,
    roomType: "Executive Suite",
    price: 400,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Free Wi-Fi", "Fitness Center", "Spa"],
    contactDetails: {
      name: "Alice Johnson",
      email: "alice.j@example.com",
      phone: "+1 123-456-7890",
    },
  },
  {
    hotelName: "Sunset View Resort",
    location: "Countryside",
    checkInDate: "2023-12-01",
    checkOutDate: "2023-12-05",
    numberOfGuests: 1,
    roomType: "Standard Single Room",
    price: 150,
    currency: "EUR",
    bookingStatus: "Pending",
    amenities: ["Outdoor Pool", "Tennis Court"],
    contactDetails: {
      name: "Bob Smith",
      email: "bob.smith@example.com",
      phone: "+44 20 1234 5678",
    },
  },
  {
    hotelName: "Mountain Lodge",
    location: "Alpine Region",
    checkInDate: "2023-11-25",
    checkOutDate: "2023-11-30",
    numberOfGuests: 3,
    roomType: "Chalet",
    price: 350,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Ski Access", "Hot Tub", "Mountain View"],
    contactDetails: {
      name: "Emma Davis",
      email: "emma.d@example.com",
      phone: "+1 987-654-3210",
    },
  },
  {
    hotelName: "Urban Retreat Inn",
    location: "City Center",
    checkInDate: "2023-12-10",
    checkOutDate: "2023-12-15",
    numberOfGuests: 2,
    roomType: "Deluxe King Room",
    price: 250,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Free Breakfast", "Business Center"],
    contactDetails: {
      name: "Michael Adams",
      email: "michael.a@example.com",
      phone: "+1 555-123-4567",
    },
  },
  {
    hotelName: "Beachfront Paradise Resort",
    location: "Oceanfront",
    checkInDate: "2023-12-20",
    checkOutDate: "2023-12-25",
    numberOfGuests: 4,
    roomType: "Family Bungalow",
    price: 600,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Private Beach", "Water Sports", "Kids Playground"],
    contactDetails: {
      name: "Sophia Wilson",
      email: "sophia.w@example.com",
      phone: "+1 333-789-0123",
    },
  },
  {
    hotelName: "Historic Manor House",
    location: "Countryside",
    checkInDate: "2023-11-05",
    checkOutDate: "2023-11-10",
    numberOfGuests: 2,
    roomType: "Classic Double Room",
    price: 180,
    currency: "EUR",
    bookingStatus: "Confirmed",
    amenities: ["Garden View", "Library"],
    contactDetails: {
      name: "David Brown",
      email: "david.b@example.com",
      phone: "+44 20 9876 5432",
    },
  },
  {
    hotelName: "Ski Chalet Resort",
    location: "Mountain Village",
    checkInDate: "2023-10-20",
    checkOutDate: "2023-10-25",
    numberOfGuests: 3,
    roomType: "Ski Suite",
    price: 300,
    currency: "EUR",
    bookingStatus: "Confirmed",
    amenities: ["Ski-in/Ski-out", "Sauna"],
    contactDetails: {
      name: "Olivia Miller",
      email: "olivia.m@example.com",
      phone: "+44 20 1111 2222",
    },
  },
  {
    hotelName: "Riverside Retreat",
    location: "Riverbank",
    checkInDate: "2023-10-10",
    checkOutDate: "2023-10-15",
    numberOfGuests: 1,
    roomType: "River View Room",
    price: 120,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Scenic Views", "Bike Rental"],
    contactDetails: {
      name: "William Turner",
      email: "william.t@example.com",
      phone: "+1 888-765-4321",
    },
  },
  {
    hotelName: "Artistic Boutique Hotel",
    location: "Art District",
    checkInDate: "2023-09-15",
    checkOutDate: "2023-09-20",
    numberOfGuests: 2,
    roomType: "Artistic Suite",
    price: 280,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Art Gallery", "Café"],
    contactDetails: {
      name: "Eva Garcia",
      email: "eva.g@example.com",
      phone: "+1 777-222-3333",
    },
  },
  {
    hotelName: "Forest Cabin Retreat",
    location: "Wooded Area",
    checkInDate: "2023-09-01",
    checkOutDate: "2023-09-05",
    numberOfGuests: 2,
    roomType: "Cozy Cabin",
    price: 200,
    currency: "USD",
    bookingStatus: "Confirmed",
    amenities: ["Nature Trails", "Campfire Area"],
    contactDetails: {
      name: "Noah Hernandez",
      email: "noah.h@example.com",
      phone: "+1 555-987-6543",
    },
  },
];

export const categoryArray = [
  {
    id: 1,
    name: "Honeymoon",
  },
  {
    id: 2,
    name: "Couple",
  },
  {
    id: 3,
    name: "Family",
  },
  {
    id: 4,
    name: "Group",
  },
  {
    id: 5,
    name: "EMI",
  },
];
